sudo: required
dist: trusty
group: edge
language: node_js
node_js:
  - "6.10"

#before_install:
#  - export CHROME_BIN=chromium-browser
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start

before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb

env:
  - PACKAGE=http

branches:
  only:
    - master

before_script:
#- cd $PACKAGE
- npm install -g codecov
- npm install
- ng lint
- npm run build
- ng test --watch=false --code-coverage
- npm run e2e --watch=false
script:
- codecov

notifications:
  email:
    on_failure: di.lammers@lvm.de
    on_success: di.lammers@lvm.de
